<?php

namespace Database\Seeders;

use App\Models\ProtectedArea;
use Illuminate\Database\Seeder;

class ProtectedAreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $areas = [
            // ==================== PARQUES NACIONALES ====================
            [
                'name' => 'Parque Nacional de Doñana',
                'wdpa_id' => '555547955',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 36.7500,
                'lat_max' => 37.1500,
                'long_min' => -6.6500,
                'long_max' => -6.2000,
                'description' => 'Uno de los espacios naturales más importantes de Europa. Alberga gran diversidad de ecosistemas: marismas, dunas, cotos y vera.',
                'area_km2' => 543.00,
                'region' => 'Andalucía',
                'established_year' => 1969,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de Sierra Nevada',
                'wdpa_id' => '555547956',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 36.9000,
                'lat_max' => 37.2000,
                'long_min' => -3.6000,
                'long_max' => -2.6000,
                'description' => 'El macizo montañoso de mayor altitud de Europa occidental. Contiene el pico Mulhacén (3.479 m).',
                'area_km2' => 858.33,
                'region' => 'Andalucía',
                'established_year' => 1999,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de los Picos de Europa',
                'wdpa_id' => '555547957',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 43.1000,
                'lat_max' => 43.3500,
                'long_min' => -5.1000,
                'long_max' => -4.4000,
                'description' => 'Primer Parque Nacional de España (1918). Impresionante macizo calcáreo con profundas gargantas y cumbres.',
                'area_km2' => 674.55,
                'region' => 'Asturias, Cantabria, Castilla y León',
                'established_year' => 1918,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de Ordesa y Monte Perdido',
                'wdpa_id' => '555547958',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 42.5500,
                'lat_max' => 42.7500,
                'long_min' => -0.1500,
                'long_max' => 0.1500,
                'description' => 'Espectaculares cañones y paisajes de alta montaña pirenaica. Patrimonio Mundial UNESCO.',
                'area_km2' => 156.08,
                'region' => 'Aragón',
                'established_year' => 1918,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de Aigüestortes i Estany de Sant Maurici',
                'wdpa_id' => '555547959',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 42.5000,
                'lat_max' => 42.6500,
                'long_min' => 0.8500,
                'long_max' => 1.1000,
                'description' => 'Único Parque Nacional de Cataluña. Destaca por sus más de 200 lagos de origen glaciar.',
                'area_km2' => 141.19,
                'region' => 'Cataluña',
                'established_year' => 1955,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional del Teide',
                'wdpa_id' => '555547960',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 28.1500,
                'lat_max' => 28.3500,
                'long_min' => -16.7000,
                'long_max' => -16.4500,
                'description' => 'Volcán más alto de España (3.718 m). Paisaje volcánico único con gran riqueza geológica.',
                'area_km2' => 189.90,
                'region' => 'Canarias',
                'established_year' => 1954,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de la Caldera de Taburiente',
                'wdpa_id' => '555547961',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 28.6800,
                'lat_max' => 28.7800,
                'long_min' => -17.9200,
                'long_max' => -17.8000,
                'description' => 'Gran depresión de origen erosivo rodeada de cumbres. Rica vegetación de laurisilva y pinar canario.',
                'area_km2' => 46.90,
                'region' => 'Canarias',
                'established_year' => 1954,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de Garajonay',
                'wdpa_id' => '555547962',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 28.0800,
                'lat_max' => 28.1500,
                'long_min' => -17.2800,
                'long_max' => -17.1800,
                'description' => 'Alberga la mejor muestra de laurisilva, bosque subtropical húmedo. Patrimonio Mundial UNESCO.',
                'area_km2' => 39.84,
                'region' => 'Canarias',
                'established_year' => 1981,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de Timanfaya',
                'wdpa_id' => '555547963',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 28.9800,
                'lat_max' => 29.0500,
                'long_min' => -13.8500,
                'long_max' => -13.7200,
                'description' => 'Paisaje volcánico de las erupciones del siglo XVIII. Las Montañas del Fuego.',
                'area_km2' => 51.07,
                'region' => 'Canarias',
                'established_year' => 1974,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de Cabañeros',
                'wdpa_id' => '555547964',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 39.3000,
                'lat_max' => 39.5500,
                'long_min' => -4.6500,
                'long_max' => -4.2500,
                'description' => 'Mejor representación de bosque mediterráneo ibérico. Importante para grandes rapaces y ungulados.',
                'area_km2' => 408.56,
                'region' => 'Castilla-La Mancha',
                'established_year' => 1995,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de las Tablas de Daimiel',
                'wdpa_id' => '555547965',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 39.1200,
                'lat_max' => 39.1800,
                'long_min' => -3.7200,
                'long_max' => -3.6200,
                'description' => 'Último representante de tablas fluviales, ecosistema prácticamente único en Europa.',
                'area_km2' => 30.30,
                'region' => 'Castilla-La Mancha',
                'established_year' => 1973,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de Monfragüe',
                'wdpa_id' => '555547966',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 39.7500,
                'lat_max' => 39.9500,
                'long_min' => -6.1500,
                'long_max' => -5.8000,
                'description' => 'Referente mundial para observación de aves. Mayor colonia de buitre negro del mundo.',
                'area_km2' => 181.18,
                'region' => 'Extremadura',
                'established_year' => 2007,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional Marítimo-Terrestre del Archipiélago de Cabrera',
                'wdpa_id' => '555547967',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 39.0800,
                'lat_max' => 39.2500,
                'long_min' => 2.8500,
                'long_max' => 3.0500,
                'description' => 'Archipiélago mediterráneo de gran valor natural. Importante para aves marinas y fondos marinos.',
                'area_km2' => 100.21,
                'region' => 'Islas Baleares',
                'established_year' => 1991,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional Marítimo-Terrestre de las Islas Atlánticas de Galicia',
                'wdpa_id' => '555547968',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 42.0500,
                'lat_max' => 42.4500,
                'long_min' => -9.0500,
                'long_max' => -8.7500,
                'description' => 'Archipiélagos de Cíes, Ons, Sálvora y Cortegada. Ecosistemas marinos de gran riqueza.',
                'area_km2' => 84.80,
                'region' => 'Galicia',
                'established_year' => 2002,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de la Sierra de Guadarrama',
                'wdpa_id' => '555547969',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 40.7000,
                'lat_max' => 41.0500,
                'long_min' => -4.2000,
                'long_max' => -3.7500,
                'description' => 'Sistema montañoso con ecosistemas de alta montaña mediterránea. Peñalara (2.428 m).',
                'area_km2' => 339.60,
                'region' => 'Madrid, Castilla y León',
                'established_year' => 2013,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Parque Nacional de la Sierra de las Nieves',
                'wdpa_id' => '555547970',
                'protection_type' => 'Parque Nacional',
                'iucn_category' => 'II',
                'designation' => 'Parque Nacional',
                'lat_min' => 36.6000,
                'lat_max' => 36.8000,
                'long_min' => -5.1000,
                'long_max' => -4.8000,
                'description' => 'Alberga los mejores pinsapares del mundo. Reserva de la Biosfera.',
                'area_km2' => 230.00,
                'region' => 'Andalucía',
                'established_year' => 2021,
                'source' => 'MITECO',
                'active' => true,
            ],

            // ==================== PARQUES NATURALES ====================
            [
                'name' => 'Parque Natural de Cazorla, Segura y Las Villas',
                'wdpa_id' => '555548001',
                'protection_type' => 'Parque Natural',
                'iucn_category' => 'V',
                'designation' => 'Parque Natural',
                'lat_min' => 37.8000,
                'lat_max' => 38.4500,
                'long_min' => -3.1000,
                'long_max' => -2.4000,
                'description' => 'Mayor espacio protegido de España. Nacimiento del río Guadalquivir. Reserva de la Biosfera.',
                'area_km2' => 2099.20,
                'region' => 'Andalucía',
                'established_year' => 1986,
                'source' => 'Junta de Andalucía',
                'active' => true,
            ],
            [
                'name' => 'Parque Natural de Somiedo',
                'wdpa_id' => '555548002',
                'protection_type' => 'Parque Natural',
                'iucn_category' => 'V',
                'designation' => 'Parque Natural',
                'lat_min' => 42.9500,
                'lat_max' => 43.1500,
                'long_min' => -6.4000,
                'long_max' => -5.9500,
                'description' => 'Uno de los mejores refugios del oso pardo cantábrico. Lagos glaciares y brañas.',
                'area_km2' => 291.85,
                'region' => 'Asturias',
                'established_year' => 1988,
                'source' => 'Principado de Asturias',
                'active' => true,
            ],
            [
                'name' => 'Parque Natural del Delta del Ebro',
                'wdpa_id' => '555548003',
                'protection_type' => 'Parque Natural',
                'iucn_category' => 'V',
                'designation' => 'Parque Natural',
                'lat_min' => 40.5500,
                'lat_max' => 40.8000,
                'long_min' => 0.5500,
                'long_max' => 0.9500,
                'description' => 'Mayor zona húmeda de Cataluña. Importantísimo para aves acuáticas.',
                'area_km2' => 77.36,
                'region' => 'Cataluña',
                'established_year' => 1983,
                'source' => 'Generalitat de Catalunya',
                'active' => true,
            ],
            [
                'name' => 'Parque Natural de la Albufera de Valencia',
                'wdpa_id' => '555548004',
                'protection_type' => 'Parque Natural',
                'iucn_category' => 'V',
                'designation' => 'Parque Natural',
                'lat_min' => 39.2500,
                'lat_max' => 39.4500,
                'long_min' => -0.4000,
                'long_max' => -0.2500,
                'description' => 'Lago costero de gran importancia ecológica. Cultivo tradicional de arroz.',
                'area_km2' => 211.20,
                'region' => 'Comunidad Valenciana',
                'established_year' => 1986,
                'source' => 'Generalitat Valenciana',
                'active' => true,
            ],
            [
                'name' => 'Parque Natural de las Hoces del Río Duratón',
                'wdpa_id' => '555548005',
                'protection_type' => 'Parque Natural',
                'iucn_category' => 'V',
                'designation' => 'Parque Natural',
                'lat_min' => 41.2500,
                'lat_max' => 41.3500,
                'long_min' => -3.9000,
                'long_max' => -3.7500,
                'description' => 'Espectacular cañón con meandros y cortados. Colonia de buitre leonado.',
                'area_km2' => 51.66,
                'region' => 'Castilla y León',
                'established_year' => 1989,
                'source' => 'Junta de Castilla y León',
                'active' => true,
            ],

            // ==================== RESERVAS DE LA BIOSFERA ====================
            [
                'name' => 'Reserva de la Biosfera de Urdaibai',
                'wdpa_id' => '555548010',
                'protection_type' => 'Reserva de la Biosfera',
                'iucn_category' => 'V',
                'designation' => 'Reserva de la Biosfera',
                'lat_min' => 43.3000,
                'lat_max' => 43.4500,
                'long_min' => -2.7500,
                'long_max' => -2.5000,
                'description' => 'Estuario del río Oka. Importante humedal del País Vasco.',
                'area_km2' => 220.00,
                'region' => 'País Vasco',
                'established_year' => 1984,
                'source' => 'UNESCO',
                'active' => true,
            ],
            [
                'name' => 'Reserva de la Biosfera de Menorca',
                'wdpa_id' => '555548011',
                'protection_type' => 'Reserva de la Biosfera',
                'iucn_category' => 'VI',
                'designation' => 'Reserva de la Biosfera',
                'lat_min' => 39.8000,
                'lat_max' => 40.1000,
                'long_min' => 3.7500,
                'long_max' => 4.3500,
                'description' => 'Toda la isla de Menorca. Modelo de conservación y desarrollo sostenible.',
                'area_km2' => 711.85,
                'region' => 'Islas Baleares',
                'established_year' => 1993,
                'source' => 'UNESCO',
                'active' => true,
            ],

            // ==================== ZEPAS (Zonas de Especial Protección para las Aves) ====================
            [
                'name' => 'ZEPA Llanos de Cáceres y Sierra de Fuentes',
                'wdpa_id' => '555548020',
                'protection_type' => 'ZEPA',
                'iucn_category' => 'IV',
                'designation' => 'Zona de Especial Protección para las Aves',
                'lat_min' => 39.2500,
                'lat_max' => 39.5500,
                'long_min' => -6.5500,
                'long_max' => -6.1500,
                'description' => 'Importante zona esteparia para avutarda, sisón y cernícalo primilla.',
                'area_km2' => 696.90,
                'region' => 'Extremadura',
                'established_year' => 1989,
                'source' => 'Red Natura 2000',
                'active' => true,
            ],
            [
                'name' => 'ZEPA Alto Guadiato',
                'wdpa_id' => '555548021',
                'protection_type' => 'ZEPA',
                'iucn_category' => 'IV',
                'designation' => 'Zona de Especial Protección para las Aves',
                'lat_min' => 38.2000,
                'lat_max' => 38.4500,
                'long_min' => -5.4000,
                'long_max' => -5.0000,
                'description' => 'Dehesas y pastizales. Refugio de águila imperial ibérica y buitre negro.',
                'area_km2' => 419.32,
                'region' => 'Andalucía',
                'established_year' => 2002,
                'source' => 'Red Natura 2000',
                'active' => true,
            ],

            // ==================== HUMEDALES RAMSAR ====================
            [
                'name' => 'Humedal Ramsar Lagunas de Villafáfila',
                'wdpa_id' => '555548030',
                'protection_type' => 'Humedal Ramsar',
                'iucn_category' => 'IV',
                'designation' => 'Humedal de Importancia Internacional',
                'lat_min' => 41.8000,
                'lat_max' => 41.9500,
                'long_min' => -5.7000,
                'long_max' => -5.5000,
                'description' => 'Complejo lagunar endorreico. Mayor población invernante de avutardas de Europa.',
                'area_km2' => 32.82,
                'region' => 'Castilla y León',
                'established_year' => 1987,
                'source' => 'Convenio Ramsar',
                'active' => true,
            ],
            [
                'name' => 'Humedal Ramsar Marismas del Odiel',
                'wdpa_id' => '555548031',
                'protection_type' => 'Humedal Ramsar',
                'iucn_category' => 'IV',
                'designation' => 'Humedal de Importancia Internacional',
                'lat_min' => 37.1500,
                'lat_max' => 37.3000,
                'long_min' => -7.0500,
                'long_max' => -6.8500,
                'description' => 'Estuario de los ríos Tinto y Odiel. Segunda colonia de espátulas de Europa.',
                'area_km2' => 72.40,
                'region' => 'Andalucía',
                'established_year' => 1989,
                'source' => 'Convenio Ramsar',
                'active' => true,
            ],
            [
                'name' => 'Humedal Ramsar Mar Menor',
                'wdpa_id' => '555548032',
                'protection_type' => 'Humedal Ramsar',
                'iucn_category' => 'IV',
                'designation' => 'Humedal de Importancia Internacional',
                'lat_min' => 37.6500,
                'lat_max' => 37.8500,
                'long_min' => -0.9500,
                'long_max' => -0.6500,
                'description' => 'Laguna costera hipersalina más grande de Europa. Importancia para aves acuáticas.',
                'area_km2' => 135.00,
                'region' => 'Región de Murcia',
                'established_year' => 1994,
                'source' => 'Convenio Ramsar',
                'active' => true,
            ],

            // ==================== MONUMENTOS NATURALES ====================
            [
                'name' => 'Monumento Natural de Los Barruecos',
                'wdpa_id' => '555548040',
                'protection_type' => 'Monumento Natural',
                'iucn_category' => 'III',
                'designation' => 'Monumento Natural',
                'lat_min' => 39.3800,
                'lat_max' => 39.4200,
                'long_min' => -6.5200,
                'long_max' => -6.4800,
                'description' => 'Espectaculares formaciones graníticas y charcas. Colonia de cigüeña blanca.',
                'area_km2' => 3.19,
                'region' => 'Extremadura',
                'established_year' => 1996,
                'source' => 'Junta de Extremadura',
                'active' => true,
            ],
            [
                'name' => 'Monumento Natural Cueva de los Murciélagos',
                'wdpa_id' => '555548041',
                'protection_type' => 'Monumento Natural',
                'iucn_category' => 'III',
                'designation' => 'Monumento Natural',
                'lat_min' => 37.4200,
                'lat_max' => 37.4400,
                'long_min' => -4.3200,
                'long_max' => -4.3000,
                'description' => 'Importante refugio de murciélagos cavernícolas. Pinturas rupestres paleolíticas.',
                'area_km2' => 0.32,
                'region' => 'Andalucía',
                'established_year' => 2001,
                'source' => 'Junta de Andalucía',
                'active' => true,
            ],

            // ==================== ÁREAS MARINAS PROTEGIDAS ====================
            [
                'name' => 'Área Marina Protegida El Cachucho',
                'wdpa_id' => '555548050',
                'protection_type' => 'Área Marina Protegida',
                'iucn_category' => 'IV',
                'designation' => 'Área Marina Protegida',
                'lat_min' => 43.8000,
                'lat_max' => 44.3500,
                'long_min' => -5.5000,
                'long_max' => -4.0000,
                'description' => 'Primera área marina protegida de España. Montaña submarina con alta biodiversidad.',
                'area_km2' => 2348.00,
                'region' => 'Asturias (Mar Cantábrico)',
                'established_year' => 2011,
                'source' => 'MITECO',
                'active' => true,
            ],
            [
                'name' => 'Reserva Marina de Cabo de Palos - Islas Hormigas',
                'wdpa_id' => '555548051',
                'protection_type' => 'Área Marina Protegida',
                'iucn_category' => 'IV',
                'designation' => 'Reserva Marina',
                'lat_min' => 37.6000,
                'lat_max' => 37.6800,
                'long_min' => -0.7200,
                'long_max' => -0.6200,
                'description' => 'Una de las reservas marinas más importantes del Mediterráneo. Rica ictiofauna.',
                'area_km2' => 19.31,
                'region' => 'Región de Murcia',
                'established_year' => 1995,
                'source' => 'MITECO',
                'active' => true,
            ],
        ];

        foreach ($areas as $data) {
            ProtectedArea::updateOrCreate(
                ['wdpa_id' => $data['wdpa_id']],
                $data
            );
        }

        $count = count($areas);
        $this->command->info("Se han creado {$count} áreas protegidas en la base de datos.");

        // Resumen por tipo
        $byType = collect($areas)->groupBy('protection_type')->map->count();
        foreach ($byType as $type => $num) {
            $this->command->info("  - {$type}: {$num}");
        }
    }
}