<?php

namespace Database\Seeders;

use App\Models\Species;
use Illuminate\Database\Seeder;

class SpeciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $species = [
            // ==================== MAMÍFEROS ====================
            [
                'scientific_name' => 'Lynx pardinus',
                'common_name' => 'Lince ibérico',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Ursus arctos',
                'common_name' => 'Oso pardo',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2017,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Canis lupus',
                'common_name' => 'Lobo ibérico',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2018,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Mustela lutreola',
                'common_name' => 'Visón europeo',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'CR',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Lutra lutra',
                'common_name' => 'Nutria',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Felis silvestris',
                'common_name' => 'Gato montés',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2022,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Capra pyrenaica',
                'common_name' => 'Cabra montés',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2020,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Monachus monachus',
                'common_name' => 'Foca monje del Mediterráneo',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2015,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Rhinolophus ferrumequinum',
                'common_name' => 'Murciélago grande de herradura',
                'taxon_group' => 'Mamíferos',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2020,
                'cites_appendix' => null,
                'is_protected' => true,
            ],

            // ==================== AVES ====================
            [
                'scientific_name' => 'Aquila adalberti',
                'common_name' => 'Águila imperial ibérica',
                'taxon_group' => 'Aves',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Gypaetus barbatus',
                'common_name' => 'Quebrantahuesos',
                'taxon_group' => 'Aves',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Aegypius monachus',
                'common_name' => 'Buitre negro',
                'taxon_group' => 'Aves',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Gyps fulvus',
                'common_name' => 'Buitre leonado',
                'taxon_group' => 'Aves',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Neophron percnopterus',
                'common_name' => 'Alimoche',
                'taxon_group' => 'Aves',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Ciconia nigra',
                'common_name' => 'Cigüeña negra',
                'taxon_group' => 'Aves',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2019,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Otis tarda',
                'common_name' => 'Avutarda',
                'taxon_group' => 'Aves',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Tetrax tetrax',
                'common_name' => 'Sisón común',
                'taxon_group' => 'Aves',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Marmaronetta angustirostris',
                'common_name' => 'Cerceta pardilla',
                'taxon_group' => 'Aves',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2018,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Oxyura leucocephala',
                'common_name' => 'Malvasía cabeciblanca',
                'taxon_group' => 'Aves',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2018,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Fulica cristata',
                'common_name' => 'Focha moruna',
                'taxon_group' => 'Aves',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2016,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Pterocles alchata',
                'common_name' => 'Ganga ibérica',
                'taxon_group' => 'Aves',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2019,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Bubo bubo',
                'common_name' => 'Búho real',
                'taxon_group' => 'Aves',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Milvus milvus',
                'common_name' => 'Milano real',
                'taxon_group' => 'Aves',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Falco peregrinus',
                'common_name' => 'Halcón peregrino',
                'taxon_group' => 'Aves',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2021,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],

            // ==================== REPTILES ====================
            [
                'scientific_name' => 'Testudo graeca',
                'common_name' => 'Tortuga mora',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2017,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Testudo hermanni',
                'common_name' => 'Tortuga mediterránea',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2017,
                'cites_appendix' => 'II',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Emys orbicularis',
                'common_name' => 'Galápago europeo',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Mauremys leprosa',
                'common_name' => 'Galápago leproso',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Caretta caretta',
                'common_name' => 'Tortuga boba',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2017,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Chelonia mydas',
                'common_name' => 'Tortuga verde',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2004,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Dermochelys coriacea',
                'common_name' => 'Tortuga laúd',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2013,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Vipera latastei',
                'common_name' => 'Víbora hocicuda',
                'taxon_group' => 'Reptiles',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],

            // ==================== ANFIBIOS ====================
            [
                'scientific_name' => 'Salamandra salamandra',
                'common_name' => 'Salamandra común',
                'taxon_group' => 'Anfibios',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Chioglossa lusitanica',
                'common_name' => 'Salamandra rabilarga',
                'taxon_group' => 'Anfibios',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Calotriton arnoldi',
                'common_name' => 'Tritón del Montseny',
                'taxon_group' => 'Anfibios',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'CR',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Alytes obstetricans',
                'common_name' => 'Sapo partero común',
                'taxon_group' => 'Anfibios',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Rana iberica',
                'common_name' => 'Rana patilarga',
                'taxon_group' => 'Anfibios',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'VU',
                'iucn_assessment_year' => 2009,
                'cites_appendix' => null,
                'is_protected' => true,
            ],

            // ==================== PECES ====================
            [
                'scientific_name' => 'Acipenser sturio',
                'common_name' => 'Esturión atlántico',
                'taxon_group' => 'Peces',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'CR',
                'iucn_assessment_year' => 2010,
                'cites_appendix' => 'I',
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Anaecypris hispanica',
                'common_name' => 'Jarabugo',
                'taxon_group' => 'Peces',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2006,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Aphanius iberus',
                'common_name' => 'Fartet',
                'taxon_group' => 'Peces',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2006,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Valencia hispanica',
                'common_name' => 'Samaruc',
                'taxon_group' => 'Peces',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'CR',
                'iucn_assessment_year' => 2006,
                'cites_appendix' => null,
                'is_protected' => true,
            ],

            // ==================== INVERTEBRADOS ====================
            [
                'scientific_name' => 'Margaritifera margaritifera',
                'common_name' => 'Mejillón de río',
                'taxon_group' => 'Invertebrados',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2017,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Lucanus cervus',
                'common_name' => 'Ciervo volante',
                'taxon_group' => 'Invertebrados',
                'boe_status' => 'Régimen de protección especial',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2014,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Osmoderma eremita',
                'common_name' => 'Escarabajo eremita',
                'taxon_group' => 'Invertebrados',
                'boe_status' => 'Vulnerable',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'NT',
                'iucn_assessment_year' => 2010,
                'cites_appendix' => null,
                'is_protected' => true,
            ],

            // ==================== FLORA ====================
            [
                'scientific_name' => 'Narcissus pseudonarcissus nobilis',
                'common_name' => 'Narciso de los prados',
                'taxon_group' => 'Flora',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => null,
                'iucn_assessment_year' => null,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Silene hifacensis',
                'common_name' => 'Silene de Ifach',
                'taxon_group' => 'Flora',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'CR',
                'iucn_assessment_year' => 2011,
                'cites_appendix' => null,
                'is_protected' => true,
            ],
            [
                'scientific_name' => 'Borderea chouardii',
                'common_name' => 'Borderea del Turbón',
                'taxon_group' => 'Flora',
                'boe_status' => 'En peligro de extinción',
                'boe_law_ref' => 'Real Decreto 139/2011',
                'iucn_category' => 'CR',
                'iucn_assessment_year' => 2011,
                'cites_appendix' => null,
                'is_protected' => true,
            ],

            // ==================== ESPECIES EXÓTICAS INVASORAS (EEI) ====================
            [
                'scientific_name' => 'Trachemys scripta',
                'common_name' => 'Galápago de Florida',
                'taxon_group' => 'Reptiles',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2011,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Procyon lotor',
                'common_name' => 'Mapache',
                'taxon_group' => 'Mamíferos',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2016,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Neovison vison',
                'common_name' => 'Visón americano',
                'taxon_group' => 'Mamíferos',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2016,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Myocastor coypus',
                'common_name' => 'Coipú',
                'taxon_group' => 'Mamíferos',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2016,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Psittacula krameri',
                'common_name' => 'Cotorra de Kramer',
                'taxon_group' => 'Aves',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2019,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Myiopsitta monachus',
                'common_name' => 'Cotorra argentina',
                'taxon_group' => 'Aves',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2018,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Ailanthus altissima',
                'common_name' => 'Árbol del cielo',
                'taxon_group' => 'Flora',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => null,
                'iucn_assessment_year' => null,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Carpobrotus edulis',
                'common_name' => 'Uña de gato',
                'taxon_group' => 'Flora',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => null,
                'iucn_assessment_year' => null,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Cortaderia selloana',
                'common_name' => 'Plumero de la Pampa',
                'taxon_group' => 'Flora',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => null,
                'iucn_assessment_year' => null,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Silurus glanis',
                'common_name' => 'Siluro',
                'taxon_group' => 'Peces',
                'boe_status' => null,
                'boe_law_ref' => 'Real Decreto 630/2013 (Catálogo EEI)',
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2010,
                'cites_appendix' => null,
                'is_protected' => false,
            ],

            // ==================== ESPECIES CINEGÉTICAS (no protegidas) ====================
            [
                'scientific_name' => 'Sus scrofa',
                'common_name' => 'Jabalí',
                'taxon_group' => 'Mamíferos',
                'boe_status' => null,
                'boe_law_ref' => null,
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2016,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Cervus elaphus',
                'common_name' => 'Ciervo común',
                'taxon_group' => 'Mamíferos',
                'boe_status' => null,
                'boe_law_ref' => null,
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2016,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Oryctolagus cuniculus',
                'common_name' => 'Conejo europeo',
                'taxon_group' => 'Mamíferos',
                'boe_status' => null,
                'boe_law_ref' => null,
                'iucn_category' => 'EN',
                'iucn_assessment_year' => 2019,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Lepus granatensis',
                'common_name' => 'Liebre ibérica',
                'taxon_group' => 'Mamíferos',
                'boe_status' => null,
                'boe_law_ref' => null,
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2019,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Alectoris rufa',
                'common_name' => 'Perdiz roja',
                'taxon_group' => 'Aves',
                'boe_status' => null,
                'boe_law_ref' => null,
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2018,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
            [
                'scientific_name' => 'Coturnix coturnix',
                'common_name' => 'Codorniz común',
                'taxon_group' => 'Aves',
                'boe_status' => null,
                'boe_law_ref' => null,
                'iucn_category' => 'LC',
                'iucn_assessment_year' => 2019,
                'cites_appendix' => null,
                'is_protected' => false,
            ],
        ];

        foreach ($species as $data) {
            Species::updateOrCreate(
                ['scientific_name' => $data['scientific_name']],
                $data
            );
        }

        $this->command->info('Se han creado ' . count($species) . ' especies en la base de datos.');
        
        $protected = Species::where('is_protected', true)->count();
        $notProtected = Species::where('is_protected', false)->count();
        $this->command->info("  - Protegidas: {$protected}");
        $this->command->info("  - No protegidas (EEI/cinegéticas): {$notProtected}");
    }
}